#!/bin/bash

ENTRY_POINT_ASSEMBLY="dotnet-reptile.dll"

get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     # While $SOURCE is a symlink, resolve it
     while [ -h "$SOURCE" ]; do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     
     SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
}

get_script_dir

dotnet "$SCRIPT_DIR/$ENTRY_POINT_ASSEMBLY"
